# Generated by Django 4.2.24 on 2026-02-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="audio/"),
        ),
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="video/"),
        ),
    ]
